"""add password column to usuarios

Revision ID: 188990c28474
Revises: 
Create Date: 2024-12-01 21:51:39.000191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '188990c28474'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('password', sa.String(), nullable=True))
    op.add_column('usuarios', sa.Column('role', sa.String(), nullable=True))
    op.drop_column('usuarios', 'cps')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('cps', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('usuarios', 'role')
    op.drop_column('usuarios', 'password')
    # ### end Alembic commands ###
